version: "3.8"

services:
  fastapi-prediccion:
    build: .
    container_name: fastapi-prediccion
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped